version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/NewsBytes
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: ec2-user
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: ec2-user